/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Campaign {
	amount_raised: Amount;
	avatar: Image;
	cause_id: string;
	description: string;
	donate_url: string;
	fundraising_event_id: string;
	goal: Amount;
	has_schedule: boolean;
	id: string;
	inserted_at: string;
	legacy_id: number;
	livestream: {
		channel: string;
		type: string;
		[k: string]: unknown;
	};
	name: string;
	original_goal: Amount;
	published_at: string;
	retired_at: string | null;
	slug: string;
	status: string;
	supporting_type: string;
	total_amount_raised: Amount;
	updated_at: string;
	url: string;
	user: {
		avatar: Image;
		description: string;
		id: string;
		legacy_id: number;
		slug: string;
		social: {
			discord?: string;
			facebook?: string;
			instagram?: string;
			snapchat?: string;
			tiktok?: string;
			twitch?: string;
			twitter?: string;
			website?: string;
			youtube?: string;
			[k: string]: unknown;
		};
		total_amount_raised: Amount;
		url: string;
		username: string;
		[k: string]: unknown;
	};
	user_id: string;
	[k: string]: unknown;
}
export interface Amount {
	currency: string;
	value: string;
	[k: string]: unknown;
}
export interface Image {
	alt: string;
	height: number;
	src: string;
	width: number;
	[k: string]: unknown;
}
