/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	/**
	 * Currency you want amounts displayed in
	 */
	displayCurrency?: string;
	/**
	 * API key for freecurrencyapi.com, used for uncommon currencies (avoids rate limiting)
	 */
	conversionRateKey?: string;
	/**
	 * Delay between dono being recieved and auto approval, only if enabled
	 */
	autoApproveTimeSec?: number;
	[k: string]: unknown;
}
