/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	tiltify_client_id?: string;
	tiltify_client_secret?: string;
	tiltify_webhook_id?: string;
	tiltify_webhook_secret?: string;
	tiltify_campaign_id?: string;
	display_currency?: string;
	/**
	 * Key for currency API, uses hardcoded values as a fallback
	 */
	freecurrencyapi_key?: string;
	[k: string]: unknown;
}
