/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Donors = {
	amount: Amount;
	avatar?: Image;
	id: string;
	name: string;
	url: string;
	[k: string]: unknown;
}[];

export interface Amount {
	currency: string;
	value: string;
	[k: string]: unknown;
}
export interface Image {
	alt: string;
	height: number;
	src: string;
	width: number;
	[k: string]: unknown;
}
