/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Schedule = Timeslot[];

export interface Timeslot {
	description: string | null;
	ends_at: string | null;
	id: string;
	inserted_at?: string;
	legacy_id?: number;
	name: string;
	starts_at: string;
	updated_at?: string;
	[k: string]: unknown;
}
